# -*- coding: utf-8 -*-
"""Clean-room data and model support for the IFPRI Standard CGE model."""

from .calibration import calibrate_ifpri_benchmark, validate_ifpri_calibration
from .data import load_ifpri_test_data, parse_ifpri_test_dat, resolve_ifpri_source
from .model import (
    IfpriResidualReport,
    build_ifpri_benchmark_model,
    ifpri_benchmark_residuals,
    summarize_ifpri_benchmark_residuals,
    validate_ifpri_benchmark_model,
)
from .solve import (
    IfpriReferenceComparison,
    IfpriSolveReport,
    apply_ifpri_base_closure,
    build_ifpri_base_solve_model,
    compare_ifpri_model_to_reference,
    ifpri_degrees_of_freedom,
    load_ifpri_reference_targets,
    perturb_ifpri_start,
    solve_ifpri_base,
)
from .schema import (
    IfpriBenchmarkCalibration,
    IfpriBenchmarkPrices,
    IfpriBenchmarkQuantities,
    IfpriCalibrationInputs,
    IfpriDataset,
    IfpriElasticities,
    IfpriFactorQuantities,
    IfpriHomeConsumption,
    IfpriInstitutionCalibration,
    IfpriLesCalibration,
    IfpriProductionCalibration,
    IfpriSystemCalibration,
    IfpriTaxCalibration,
    IfpriSam,
    IfpriSets,
    IfpriTaxData,
)
from .validation import (
    IfpriDataError,
    validate_dataset,
    validate_inputs,
    validate_sam,
    validate_sets,
)

__all__ = [
    "IfpriBenchmarkCalibration",
    "IfpriBenchmarkPrices",
    "IfpriBenchmarkQuantities",
    "IfpriCalibrationInputs",
    "IfpriDataError",
    "IfpriDataset",
    "IfpriElasticities",
    "IfpriFactorQuantities",
    "IfpriHomeConsumption",
    "IfpriInstitutionCalibration",
    "IfpriLesCalibration",
    "IfpriProductionCalibration",
    "IfpriResidualReport",
    "IfpriReferenceComparison",
    "IfpriSolveReport",
    "IfpriSystemCalibration",
    "IfpriTaxCalibration",
    "IfpriSam",
    "IfpriSets",
    "IfpriTaxData",
    "apply_ifpri_base_closure",
    "build_ifpri_base_solve_model",
    "compare_ifpri_model_to_reference",
    "build_ifpri_benchmark_model",
    "calibrate_ifpri_benchmark",
    "ifpri_benchmark_residuals",
    "ifpri_degrees_of_freedom",
    "load_ifpri_reference_targets",
    "load_ifpri_test_data",
    "parse_ifpri_test_dat",
    "perturb_ifpri_start",
    "solve_ifpri_base",
    "resolve_ifpri_source",
    "summarize_ifpri_benchmark_residuals",
    "validate_dataset",
    "validate_ifpri_benchmark_model",
    "validate_ifpri_calibration",
    "validate_inputs",
    "validate_sam",
    "validate_sets",
]
